name: yhwh
description: A bible aplication.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.2

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.0.0
  animate_do: ^3.3.4
  get_storage: ^2.0.0
  scroll_to_index: ^3.0.1
  font_awesome_flutter: ^10.0.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  path_provider: ^2.0.0
  diacritic: ^0.1.0
  uuid: ^4.5.1
  lazy_load_scrollview: ^1.0.0
  simple_html_css: ^5.0.0
  url_launcher: ^6.1.5
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner:
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  
  # I. CONFIGURACIÓN GENERAL (Para iOS y Android antiguo)
  image_path: "assets/icons/icon_full.png"

  # II. CONFIGURACIÓN ADAPTATIVA (Para Android moderno)
  adaptive_icon_background: "assets/icons/icon_background.png"
  adaptive_icon_foreground: "assets/icons/icon_foreground.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/portrait_logo.png

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito.ttf
    - family: Playfair
      fonts:
        - asset: fonts/Playfair.ttf